<?php 
	$titulo = 'DMV Intercâmbio';
	require_once ('header.php');
	
	require_once ('nav.php');
?>

	

				<!-- Start cssSlider.com -->
			<!-- Generated by cssSlider.com 2.0 -->
			
			<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->

			<div class="csslider1 no-autoplay ">
			
			<input name="cs_anchor1" id="cs_slide1_1" type="radio" class="cs_anchor slide" aria-labelledby="cs_slide1_1">
			<input name="cs_anchor1" id="cs_slide1_2" type="radio" class="cs_anchor slide" aria-labelledby="cs_slide1_2">
			<input name="cs_anchor1" id="cs_slide1_3" type="radio" class="cs_anchor slide" aria-labelledby="cs_slide1_3">
			<input name="cs_anchor1" id="cs_slide1_4" type="radio" class="cs_anchor slide" aria-labelledby="cs_slide1_4">
			<input name="cs_anchor1" id="cs_slide1_5" type="radio" class="cs_anchor slide" aria-labelledby="cs_slide1_5">
			<input name="cs_anchor1" id="cs_slide1_6" type="radio" class="cs_anchor slide" aria-labelledby="cs_slide1_6">
			<input name="cs_anchor1" id="cs_play1" type="radio" class="cs_anchor" checked="">
			<input name="cs_anchor1" id="cs_pause1_0" type="radio" class="cs_anchor pause">
			<input name="cs_anchor1" id="cs_pause1_1" type="radio" class="cs_anchor pause">
			<input name="cs_anchor1" id="cs_pause1_2" type="radio" class="cs_anchor pause">
			<input name="cs_anchor1" id="cs_pause1_3" type="radio" class="cs_anchor pause">
			<input name="cs_anchor1" id="cs_pause1_4" type="radio" class="cs_anchor pause">
			<input name="cs_anchor1" id="cs_pause1_5" type="radio" class="cs_anchor pause">
			<input name="cs_anchor1" id="cs_pause1_6" type="radio" class="cs_anchor pause">
			<ul>
				<li class="cs_skeleton"><img src="cssslider_files/csss_images1/mundi.png" style="width: 100%;" alt="Mapa Mundi"></li>
				<li class="num0 img slide"> <img src="cssslider_files/csss_images1/mundi.png" alt="Mundo" title="Mundo"></li>
				<li class="num1 img slide"> <img src="cssslider_files/csss_images1/eua.png" alt="Estados Unidos da América" title="Estados Unidos da América"></li>
				<li class="num2 img slide"> <img src="cssslider_files/csss_images1/espanha.png" alt="Espanha" title="Espanha"></li>
				<li class="num3 img slide"> <img src="cssslider_files/csss_images1/franca.png" alt="França" title="França"></li>
				<li class="num4 img slide"> <img src="cssslider_files/csss_images1/alemanha.png" alt="imagem do parlamento alemão, com varias bandeiras, de dia e com pessoas circulando a área" title="Alemanha"></li>
				<li class="num5 img slide"> <img src="cssslider_files/csss_images1/china.png" alt="China" title="China"></li>
				<li class="num6 img slide"> <img src="cssslider_files/csss_images1/italia.png" alt="Italia" title="Italia"></li>
			</ul><div class="cs_engine"><a href="http://cssslider.com">jquery gallery</a> by cssSlider.com v2.0</div>
			<div class="cs_description">
				<label class="num0"><span class="cs_title"><span class="cs_wrapper">Mundo</span></span></label>
				<label class="num1"><span class="cs_title"><span class="cs_wrapper">Estados Unidos da América</span></span></label>
				<label class="num2"><span class="cs_title"><span class="cs_wrapper">Espanha</span></span></label>
				<label class="num3"><span class="cs_title"><span class="cs_wrapper">França</span></span></label>
				<label class="num4"><span class="cs_title"><span class="cs_wrapper">Alemanha</span></span></label>
				<label class="num5"><span class="cs_title"><span class="cs_wrapper">China</span></span></label>
				<label class="num6"><span class="cs_title"><span class="cs_wrapper">Itália</span></span></label>
			</div>
			<div class="cs_play_pause">
				<label class="cs_play" for="cs_play1">0<span><i></i><b></b></span></label>
				<label class="cs_pause num0" for="cs_pause1_0"><span><i></i><b></b></span></label>
				<label class="cs_pause num1" for="cs_pause1_1"><span><i></i><b></b></span></label>
				<label class="cs_pause num2" for="cs_pause1_2"><span><i></i><b></b></span></label>
				<label class="cs_pause num3" for="cs_pause1_3"><span><i></i><b></b></span></label>
				<label class="cs_pause num4" for="cs_pause1_4"><span><i></i><b></b></span></label>
				<label class="cs_pause num5" for="cs_pause1_5"><span><i></i><b></b></span></label>
				<label class="cs_pause num6" for="cs_pause1_6"><span><i></i><b></b></span></label>
				</div>
		    <div class="cs_arrowprev">
				<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
				<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
				<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
				<label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
				<label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
				<label class="num5" for="cs_slide1_5"><span><i></i><b></b></span></label>
				<label class="num6" for="cs_slide1_6"><span><i></i><b></b></span></label>
			</div>
			<div class="cs_arrownext">
				<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
				<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
				<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
				<label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
				<label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
				<label class="num5" for="cs_slide1_5"><span><i></i><b></b></span></label>
				<label class="num6" for="cs_slide1_6"><span><i></i><b></b></span></label>
			</div>
			<div class="cs_bullets">
				<label class="num0" for="cs_slide1_0"> <span class="cs_point"></span>
					<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/mundi.png" alt="Mundo" title="Mundo"></span></label>
				<label class="num1" for="cs_slide1_1"> <span class="cs_point"></span>
					<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/eua.png" alt="Estados Unidos da América" title="Estados Unidos da América"></span></label>
				<label class="num2" for="cs_slide1_2"> <span class="cs_point"></span>
					<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/espanha.png" alt="Espanha" title="Espanha"></span></label>
				<label class="num3" for="cs_slide1_3"> <span class="cs_point"></span>
					<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/franca.png" alt="França" title="França"></span></label>
				<label class="num4" for="cs_slide1_4"> <span class="cs_point"></span>
					<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/alemanha.png" alt="Alemanha" title="Alemanha"></span></label>
				<label class="num5" for="cs_slide1_5"> <span class="cs_point"></span>
					<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/china.png" alt="China" title="China"></span></label>
				<label class="num6" for="cs_slide1_6"> <span class="cs_point"></span>
					<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/italia.png" alt="Italia" title="Italia"></span></label>
			</div>
			</div>
			<!-- End cssSlider.com -->

				
			<main>
					<h1>Depoimentos</h1>
					<p>
						<a href="depoimentos.html#dep_eua"><img src="imagens/depo-eua.jpg" alt="depoimento 1" id="dep1" class="depoimentos" tabindex="1"></a>
						<a href="depoimentos.html#dep_fra"><img src="imagens/depo-franca.jpg" alt="depoimento 2" id="dep2" class="depoimentos" tabindex="2"></a>
						<a href="depoimentos.html#dep_ale"><img src="imagens/depo-alemanha.jpg" alt="depoimento 3" id="dep3" class="depoimentos" tabindex="3"></a>
					</p>
					<p>
						<a href="depoimentos.html#dep_ita"><img src="imagens/depo-italia.jpg" alt="depoimento 4" id="dep4" class="depoimentos" tabindex="4"></a>
						<a href="depoimentos.html#dep_chi"><img src="imagens/depo-china.jpg" alt="depoimento 5" id="dep5" class="depoimentos" tabindex="5"></a>
						<a href="depoimentos.html#dep_esp"><img src="imagens/depo-espanha.jpg" alt="depoimento 6" id="dep6" class="depoimentos" tabindex="6"></a>
					</p>
			</main>	
			
<?php 
require_once ('footer.php');
?>	
					
			
			  
				